[book]
authors = ["k-nasa"]
language = "ja"
multilingual = false
src = "src"
title = "Rustで学ぶ非同期処理ランタイム"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/k-nasa/rust-async-book"
git-repository-icon = "fa-github"
